### ISSUE TITLE
Warped pointcloud not sure if calibration related

### ISSUE THREAD

**Issue by robinJKU** [code-iai/iai_kinect2#121] opened 2015-07-13 10:10 UTC
Hello,

I have a strange issue regarding my kinect2, when facing down about 45° at a table I get a warped pointcloud, it looks pretty much the same with and without calibration.
I calibrated the kinect using a checker board with nearly 200 images.

Setup:
![Image of Problem](https://picload.org/image/iiaciac/2015-07-1311.50.51.jpg)
Pointcloud:
![Image of Problem](https://picload.org/image/iiaciao/pointcloud.png)

Kinect SDK:

![Image of Problem](https://picload.org/image/iiordir/kinect_sdk_2.png)
![Image of Problem](https://picload.org/image/iiordia/kinect_sdk_1.png)

All other walls seem fine and the table is crucial for our demo, any information would be appreciated.

**Comment by wiedemeyer** [comment] 2015-07-13 10:49
I would guess that's exactly one of the down sides of the new Kinect and the ToF. Corners are rounded and at certain angles the measurements are incorrect. And depth measurements are also dependent on the material of the surface of objects. If you move the sensor further down, so the angle between sensor and plane gets smaller, you will probably end up with no depth values at all.
I think this is nothing that I could solve in kinect2_bridge, this (if possible) should to be addressed in the libfreenect2 driver. Maybe you can also post this on the libfreenect2 issues.
Is it possible to connect your Kinect to a Windows machine with the official SDK? I would really like to see, if it shows the same problems.

**Comment by robinJKU** [comment] 2015-07-13 11:58
Thank you for the fast reply, I will try to get a windows PC with a sufficient graphics cards connected to our kinect (the SDK needs DirectX 11 and Windows 8 if I recall correctly).
The problem is definitely the angle between the kinect and the surface, I will try some other configuration and open an issue in libfreenect2.

**Comment by robinJKU** [comment] 2015-07-14 05:46
I added 2 Screenshots from the Kinect SDK, looks like it is a ToF problem with angled surfaces.

**Comment by jeppewalther** [comment] 2015-07-14 10:44
Its is caused by multi path effects. When light from the sensor is reflected and in turn returned from a secondary surface it causes distortions. In the image below we see two setups one with a white table surface (left) and one with a black table (right)

![1436869905 28](https://cloud.githubusercontent.com/assets/456099/8671459/86cf0564-2a25-11e5-8c21-51cbfaa18948.jpg)

**Comment by lakehanne** [comment] 2015-07-14 12:33
Jepp, your issue seems more a matter of background lighting. In the presence of background light, the memory elements in the sensor receive an additional part of the signal. This would disturb the distance measurement.

**Comment by jeppewalther** [comment] 2015-07-15 11:40
I am pretty sure it is not background light from another source than the sensor. If i place a small black plate just in front of the cube, issues with curved surfaces will disappear. It is also dependent on the angle between surface and sensor. It is correct that additional parts of the IR light is distorting the signal. However the origin of that light is from the sensors IR lamps.

**Comment by robinJKU** [comment] 2015-07-28 05:10
By increasing the angle to the table I got rid of most of the distortions, seems like the kinect works best with perpendicular surfaces, so I will try switching the view angle between table and object recognition for better results.

**Closed** 2015-10-26 07:56 UTC
